version: "3"

services:
  mariadb:
    build:
      context: "_mariadb"
    container_name: 'database'
    restart: 'always'
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./_mariadb/data:/var/lib/mysql
      - ./_mariadb/logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker